databases:
  - name: dpg-ch8014msi8uhth3p33ng-a
    databaseName: wallet_db_8vt3
    user: wallet_db_8vt3_user

services:
  - type: web
    plan: free
    name: wallet
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn wallet.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dpg-ch8014msi8uhth3p33ng-a
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4