services:
  - type: web
    plan: free
    name: wallet
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn wallet.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: wallet_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4