# Generated by Django 4.0.3 on 2022-04-11 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_expense_account_alter_income_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.account')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.currency')),
            ],
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
    ]
