# Generated by Django 4.0.3 on 2022-04-11 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_cost_delete_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.account'),
        ),
    ]
