# Generated by Django 4.0.3 on 2022-04-14 12:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_account_balance_alter_account_currency_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfer',
            old_name='amount',
            new_name='from_amount',
        ),
        migrations.RemoveField(
            model_name='cost',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='income',
            name='currency',
        ),
        migrations.AddField(
            model_name='transfer',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='transfer',
            name='to_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
            preserve_default=False,
        ),
    ]
