# Generated by Django 4.0.3 on 2022-04-14 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_amount_transfer_from_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cost',
            name='description',
        ),
        migrations.RemoveField(
            model_name='income',
            name='description',
        ),
        migrations.AddField(
            model_name='cost',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.costcategory'),
        ),
        migrations.AddField(
            model_name='income',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.incomecategory'),
        ),
    ]
