# Generated by Django 4.0.3 on 2022-04-15 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_cost_description_remove_income_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cost',
            new_name='Expense',
        ),
        migrations.RenameModel(
            old_name='CostCategory',
            new_name='ExpenseCategory',
        ),
        migrations.AlterModelOptions(
            name='expensecategory',
            options={'verbose_name_plural': 'ExpenseCategories'},
        ),
    ]
