# Generated by Django 4.0.3 on 2022-04-21 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_cost_expense_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='to_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14),
        ),
    ]
