# Generated by Django 4.0.3 on 2022-06-20 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_currency_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='expensecategory',
            unique_together={('parent', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='incomecategory',
            unique_together={('parent', 'name')},
        ),
        migrations.RemoveField(
            model_name='expensecategory',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='incomecategory',
            name='slug',
        ),
    ]
