# Generated by Django 4.0.3 on 2022-07-03 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_account_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='active',
            new_name='is_active',
        ),
    ]
