# Generated by Django 4.0.3 on 2022-07-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_rename_active_account_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_transfer',
            field=models.BooleanField(default=False),
        ),
    ]
