# Generated by Django 4.0.3 on 2022-07-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_category_is_transfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('E', 'Expense'), ('I', 'Income')], max_length=2),
        ),
    ]
