# Generated by Django 4.0.3 on 2022-07-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_protected',
            field=models.BooleanField(default=False),
        ),
    ]
