# Generated by Django 4.0.3 on 2022-08-01 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_remove_account_is_loan_loan'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('user', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='loan',
            unique_together={('user', 'name')},
        ),
    ]
