# Generated by Django 4.0.3 on 2022-08-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_account_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='initial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
