# Generated by Django 4.0.3 on 2022-09-04 04:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_account_created_account_updated_loan_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpreferences',
            old_name='currency',
            new_name='primary_currency',
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_preferences', to=settings.AUTH_USER_MODEL),
        ),
    ]
