# Generated by Django 4.0.3 on 2022-09-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_rename_currency_userpreferences_primary_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='initial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
