# Generated by Django 4.0.3 on 2022-09-09 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_account_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('currency', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rate', to='main.currency')),
            ],
        ),
    ]
