# Generated by Django 4.0.3 on 2022-10-05 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='from_transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_from', to='main.transaction'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='to_transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_to', to='main.transaction'),
        ),
    ]
