# Generated by Django 4.0.3 on 2022-10-07 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_alter_transfer_from_transaction_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('user', 'name', 'is_active')},
        ),
        migrations.AlterUniqueTogether(
            name='loan',
            unique_together={('user', 'name', 'is_active')},
        ),
    ]
