# Generated by Django 4.0.3 on 2022-11-01 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_alter_transaction_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='accounts', to='main.currency'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='currency',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='loans', to='main.currency'),
        ),
    ]
