# Generated by Django 4.0.3 on 2023-01-13 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('main', '0039_alter_account_currency_alter_loan_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='content_type',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
