# Generated by Django 4.0.3 on 2023-01-15 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('main', '0040_alter_transaction_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='content_type',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.CreateModel(
            name='CreaditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('initial', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('payment_day', models.PositiveIntegerField(blank=True)),
                ('currency', models.ForeignKey(default=5, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='credit_cards', to='main.currency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='creaditcard',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('name', 'user'), name='unique card name and user when active'),
        ),
        migrations.AddConstraint(
            model_name='creaditcard',
            constraint=models.CheckConstraint(check=models.Q(('payment_day__gte', 1), ('payment_day__lte', 31)), name='payment_day_between_1-31'),
        ),
    ]
