# Generated by Django 4.0.3 on 2023-01-15 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_alter_transaction_content_type_creaditcard_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CreaditCard',
            new_name='CreditCard',
        ),
    ]
