# Generated by Django 4.0.3 on 2023-01-17 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_rename_creaditcard_creditcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='payment_day',
            field=models.PositiveIntegerField(),
        ),
    ]
