# Generated by Django 4.0.3 on 2023-01-20 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_alter_creditcard_payment_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='installments',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(check=models.Q(('installments__gte', 2), ('installments__lte', 36)), name='installments_btw_0_36'),
        ),
    ]
