# Generated by Django 4.0.3 on 2023-03-04 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('main', '0045_transaction_due_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestUserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_user_session', to='sessions.session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_user_session', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
